[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Boyu-Zhang-UOI/pml-f2026-notebooks/blob/main/class-demos/session03_numpy_arrays.ipynb)

# Session 3 deck code, assembled in slide order

**Session 3 · the in-class demo — runs on the free tier of Colab, nothing to install**

Generated by scripts/make_demo.py from the slides themselves, so it stays
honest about what the deck actually shows. Run it before class.

Each heading names the slide its cell accompanies; the outputs below were saved from a real run.

## Slide 5: The ndarray: One Type, One Block

In [1]:
import numpy as np

A = np.array([[1.0, 2.0, 3.0, 4.0],
              [5.0, 6.0, 7.0, 8.0]])
print(A)
print(type(A))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>


## Slide 6: Anatomy: shape, ndim, size, nbytes

In [2]:
print("shape   :", A.shape)
print("ndim    :", A.ndim)
print("size    :", A.size)
print("itemsize:", A.itemsize)
print("nbytes  :", A.nbytes)

shape   : (2, 4)
ndim    : 2
size    : 8
itemsize: 8
nbytes  : 64


## Slide 7: dtype: The Element Type Matters

In [3]:
ints = np.array([1, 2, 3])
floats = np.array([1, 2, 3], dtype=np.float32)
print(ints.dtype, ints.nbytes)
print(floats.dtype, floats.nbytes)
print(np.array([1, 2, 3.5]).dtype)

big = np.array([2_000_000_000], dtype=np.int32)
print(big + big)

int64 24
float32 12
float64
[-294967296]


## Slide 8: Strides: How NumPy Finds an Element

In [4]:
B = np.arange(12).reshape(3, 4)
print("shape  :", B.shape)
print("strides:", B.strides)
print("T shape  :", B.T.shape)
print("T strides:", B.T.strides)
print("same buffer:", np.shares_memory(B, B.T))

shape  : (3, 4)
strides: (32, 8)
T shape  : (4, 3)
T strides: (8, 32)
same buffer: True


## Slide 9: Worked Question: How Big Is This Batch?

In [5]:
X = np.zeros((128, 3, 32, 32),
             dtype=np.float32)   # a batch of images
print(X.size)
print(X.nbytes)
print(X.strides)

393216
1572864
(12288, 4096, 128, 4)


## Slide 10: Creating Arrays: The Routines You Will Reuse

In [6]:
print(np.arange(0, 10, 3))
print(np.linspace(0, 1, 5))
rng = np.random.default_rng(7)
print(rng.standard_normal((2, 3)).round(3))

[0 3 6 9]
[0.   0.25 0.5  0.75 1.  ]
[[ 0.001  0.299 -0.274]
 [-0.891 -0.455 -0.992]]


## Slide 11: Indexing and Slicing in Two Dimensions

In [7]:
X = np.arange(20).reshape(4, 5)
print(X[1, 3])      # one element
print(X[0])         # row 0
print(X[:, 2])      # column 2
print(X[1:3, 1:4])  # a block

8
[0 1 2 3 4]
[ 2  7 12 17]
[[ 6  7  8]
 [11 12 13]]


## Slide 12: Slices Are Views, Not Copies

In [8]:
X = np.arange(20).reshape(4, 5)
block = X[1:3, 1:4]
print("shares memory:", np.shares_memory(X, block))
block[0, 0] = -99
print("X[1, 1] is now", X[1, 1])

copied = X[1:3, 1:4].copy()
print("copy shares memory:", np.shares_memory(X, copied))

shares memory: True
X[1, 1] is now -99
copy shares memory: False


## Slide 13: Fancy and Boolean Indexing Return Copies

In [9]:
X = np.arange(20).reshape(4, 5)
rows = X[[0, 3]]
print("shares memory:", np.shares_memory(X, rows))
v = np.array([3, -1, 7, -4, 0])
print(v[v > 0])
v[v < 0] = 0
print(v)

shares memory: False
[3 7]
[3 0 7 0 0]


## Slide 14: Check Yourself #1

In [10]:
A = np.arange(10)
b = A[2:5]
b[:] = 0
print(A)
C = np.arange(10)
d = C[[2, 3, 4]]
d[:] = 0
print(C)

[0 1 0 0 0 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Slide 16: The Benchmark: Three Implementations

In [11]:
def mse_loop(y, yhat):
    total = 0.0
    for i in range(len(y)):
        total += (y[i] - yhat[i]) ** 2
    return total / len(y)

def mse_comprehension(y, yhat):
    squares = [(a - b) ** 2
               for a, b in zip(y, yhat)]
    return sum(squares) / len(y)

def mse_numpy(y, yhat):
    return ((y - yhat) ** 2).mean()

## Slide 19: Universal Functions (ufuncs)

In [12]:
u = np.array([1.0, 4.0, 9.0, 16.0])
print(np.sqrt(u))
print(np.log(u).round(3))
print(np.maximum(u, 5.0))
print(np.add.reduce(u))

[1. 2. 3. 4.]
[0.    1.386 2.197 2.773]
[ 5.  5.  9. 16.]
30.0


## Slide 20: Check Yourself #2

In [13]:
u = np.array([1.0, 4.0, 9.0, 16.0])
print(np.maximum(u, 4.0))
print(u - u.mean())

[ 4.  4.  9. 16.]
[-6.5 -3.5  1.5  8.5]


## Slide 21: Broadcasting: The Motivating Case

In [14]:
X = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])
bias = np.array([10.0, 20.0, 30.0])
print(X + bias)
print(X.shape, bias.shape, (X + bias).shape)

[[11. 22. 33.]
 [14. 25. 36.]]
(2, 3) (3,) (2, 3)


## Slide 24: Broadcasting Rule 3: Otherwise, an Error

In [15]:
print(np.broadcast_shapes((3, 4), (4,)))
print(np.broadcast_shapes((3, 1), (1, 4)))
print(np.broadcast_shapes((5, 1, 3), (4, 3)))

(3, 4)
(3, 4)
(5, 4, 3)


## Slide 26: Pitfall: (n,) Is Not (n, 1)

In [16]:
w = np.arange(3)
print(w.shape, w[:, None].shape)
print((w + w).shape)
print((w[:, None] + w).shape)
print(w[:, None] + w)

(3,) (3, 1)
(3,)
(3, 3)
[[0 1 2]
 [1 2 3]
 [2 3 4]]


## Slide 27: Check Yourself #3

In [17]:
a = np.ones((3, 4))
b = np.ones(4)
c = np.ones((3, 1))
print((a + b).shape)
print((a + c).shape)
print((b + c).shape)

(3, 4)
(3, 4)
(3, 4)


## Slide 28: Aggregation Along an Axis

In [18]:
M = np.arange(12).reshape(3, 4)
print(M.sum())
print(M.sum(axis=0), M.sum(axis=0).shape)
print(M.sum(axis=1), M.sum(axis=1).shape)
print(M.mean(axis=0))
print(M.argmax(axis=1))

66
[12 15 18 21] (4,)
[ 6 22 38] (3,)
[4. 5. 6. 7.]
[3 3 3]


## Slide 30: keepdims: Aggregate and Keep the Shape

In [19]:
print(M.sum(axis=1).shape)
print(M.sum(axis=1, keepdims=True).shape)
print(M - M.mean(axis=1, keepdims=True))

(3,)
(3, 1)
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


## Slide 31: Check Yourself #4

In [20]:
rng = np.random.default_rng(0)
X = rng.normal(size=(200, 3))  # 200 samples, 3 features
print(X.mean(axis=0).shape)
print((X - X.mean(axis=0)).shape)
print((X - X.mean(axis=1, keepdims=True)).shape)

(3,)
(200, 3)
(200, 3)


## Slide 32: Applied: Standardizing a Feature Matrix

In [21]:
rng = np.random.default_rng(3)
X = rng.normal(loc=[5.0, 100.0, -2.0],
               scale=[1.0, 25.0, 0.5], size=(200, 3))
Z = (X - X.mean(axis=0)) / X.std(axis=0)
print(X.mean(axis=0).round(3))
print(Z.mean(axis=0).round(12))
print(Z.std(axis=0).round(12))

[  5.072 102.641  -1.99 ]
[ 0. -0.  0.]
[1. 1. 1.]


## Slide 33: Applied: Pairwise Distances Without Loops

In [22]:
P = np.array([[0.0, 0.0], [3.0, 4.0], [6.0, 8.0]])
diff = P[:, None, :] - P[None, :, :]
D = np.sqrt((diff ** 2).sum(axis=-1))
print(diff.shape)
print(D)

(3, 3, 2)
[[ 0.  5. 10.]
 [ 5.  0.  5.]
 [10.  5.  0.]]
